const GLOBALS = {
    PLAYER_SPEED: 500,
    BULLET_DAMAGE: 1,
    ENEMY_DAMAGE: 1,

    SHOTGUN_FIRERATE: 300,
    PISTOL_FIRERATE: 400,
    HEAVY_MACHINE_GUN_FIRERATE: 115,

    PLAYER_BULLET_SPEED: 1400,
    ENEMY_BULLET_SPEED: 500,

    ORC_HEALTH: 3,
    NECROMANCER_HEALTH: 2,
    BIG_ZOMBIE_HEALTH: 10,
    OGRE_HEALTH: 15,
    SHAMAN_HEALTH: 2,
    DEMON_HEALTH: 250,
    TINY_ZOMBIE_HEALTH: 2,
    ZOMBIE_HEALTH: 5, 

    NECROMANCER_FIRERATE: 2000,
    SHAMAN_FIRERATE: 2000,
    DEMON_FIRERATE: 500,
    DEMON_LASER_FIRERATE: 50,

    // -- SPAWN TIMES -- //
    ORC_SPAWN_TIME: 5000,
    SHAMAN_SPAWN_TIME: 10000,
    OGRE_SPAWN_TIME: 10000,
    NECROMANCER_SPAWN_TIME: 30000,
    BIG_ZOMBIE_SPAWN_TIME: 30000,
    DEMON_SPAWN_TIME: 60000,
}

export default GLOBALS;