const GLOBALS = {
    PLAYER_SPEED: 500,
    BULLET_DAMAGE: 1,
    ENEMY_DAMAGE: 1,

    SHOTGUN_FIRERATE: 300,
    PISTOL_FIRERATE: 400,
    HEAVY_MACHINE_GUN_FIRERATE: 115,

    PLAYER_BULLET_SPEED: 1400,

    ORC_HEALTH: 3,
    NECROMANCER_HEALTH: 2,
    BIG_ZOMBIE_HEALTH: 10,
    OGRE_HEALTH: 15,
    SHAMAN_HEALTH: 2,
    DEMON_HEALTH: 250,
    TINY_ZOMBIE_HEALTH: 2,
    ZOMBIE_HEALTH: 5, 
}

export default GLOBALS;