const GLOBALS = {
    PLAYER_SPEED: 500,
    BULLET_DAMAGE: 1,
    ENEMY_DAMAGE: 1,

    SHOTGUN_FIRERATE: 300,
    SHOTGUN_AMMO: 8,
    SHOTGUN_RELOAD_TIME: 500,

    PISTOL_FIRERATE: 400,
    PISTOL_AMMO: 12,
    PISTOL_RELOAD_TIME: 1000,

    HEAVY_MACHINE_GUN_FIRERATE: 115,
    HEAVY_MACHINE_GUN_AMMO: 50,
    HEAVY_MACHINE_GUN_RELOAD_TIME: 1500,

    PLAYER_BULLET_SPEED: 1400,
}

export default GLOBALS;